[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.17"
rpc_url = "https://sepolia.infura.io/v3/588e774480844593a6340767d8df45bd"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
